"""
Pydantic schemas used to validate every LLM output before it is allowed
to move to the next LangGraph node. If validation fails, the graph
retries the node with the validation error appended to the prompt
(see nodes.py -> `with_retry`).
"""

from __future__ import annotations
from typing import List, Optional, Literal
from pydantic import BaseModel, Field, field_validator


Severity = Literal["low", "medium", "high"]
Confidence = Literal["high", "medium", "low"]


class Party(BaseModel):
    name: str
    role: str


class Clause(BaseModel):
    type: str
    present: bool
    quoted_text: Optional[str] = None
    location: Optional[str] = None
    confidence: Confidence = "low"

    @field_validator("quoted_text")
    @classmethod
    def empty_if_not_present(cls, v, info):
        # If marked not present, there should be no fabricated quote.
        if info.data.get("present") is False and v:
            raise ValueError(
                "quoted_text must be null when present=False (no fabrication allowed)"
            )
        return v


class Risk(BaseModel):
    related_clause: str
    quoted_text: str
    issue: str
    severity: Severity
    suggested_action: str


class PartyObligations(BaseModel):
    party: str
    obligations: List[str]


class ContractType(BaseModel):
    contract_type: str
    is_confident: bool
    reasoning: str


class ClauseExtractionResult(BaseModel):
    parties: List[Party]
    clauses: List[Clause]


class RiskAnalysisResult(BaseModel):
    risks: List[Risk]
    missing_standard_clauses: List[str]


class ObligationsResult(BaseModel):
    obligations_summary: List[PartyObligations]


class FinalReport(BaseModel):
    contract_type: str
    parties: List[Party]
    clauses: List[Clause]
    risks: List[Risk]
    obligations_summary: List[PartyObligations]
    missing_standard_clauses: List[str]
    executive_summary: str
    disclaimer: str = (
        "This analysis is generated by an AI system for informational purposes "
        "only and does not constitute legal advice. Consult a licensed attorney "
        "before making decisions based on this contract."
    )
